version: 2.1
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: amd64/fedora:39
    environment:
      BASH_ENV: /etc/profile.d/nextspace.sh
    steps:
      - checkout:
          path: /root/nextspace
      - run:
          name: Install build tools
          command: yum -y install sudo git openssh-clients which binutils
      - run:
          name: Install Libraries
          command: |
            cd /root/nextspace/Packaging/RedHat
            ./0.build_libraries.sh
            rm -r /root/rpmbuild/BUILD/*
            rm -r /root/rpmbuild/RPMS/*
      - run:
          name: Build and install Frameworks
          command: |
            cd /root/nextspace/Packaging/RedHat
            ./1.build_frameworks.sh
            rm -r /root/rpmbuild/BUILD/*
            rm -r /root/rpmbuild/RPMS/*
      - run:
          name: Build and install Applications
          command: |
            cd /root/nextspace/Packaging/RedHat
            ./2.build_applications.sh
            rm -r /root/rpmbuild/BUILD/*
            rm -r /root/rpmbuild/RPMS/*
          
