name: Fedora 41 RPM

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Build RPMs on Fedora 41'

jobs:
  build:
    runs-on: ubuntu-22.04
    container: amd64/fedora:41

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools
      run: dnf -y install sudo git openssh-clients which binutils binutils-gold clang
    - name: Build and install Libraries
      run: |
        cd Packaging/RedHat
        ./0.build_libraries.sh
    - name: Build and install Frameworks
      run: |
        cd Packaging/RedHat
        ./1.build_frameworks.sh
    - name: Build and install Applications
      run: |
        cd Packaging/RedHat
        ./2.build_applications.sh
